sudo: true
language: cpp

compiler:
  - g++
  - clang

before_install:
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
  - sudo add-apt-repository ppa:adrozdoff/llvm-backport
  - sudo apt-get update
  - sudo apt-get install clang-3.8

  - git clone https://github.com/bblanchon/ArduinoJson.git
  - cd ArduinoJson
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

  - git clone https://github.com/libical/libical.git
  - cd libical
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

  - git clone https://github.com/wolfSSL/wolfssl.git
  - cd wolfssl
  - sh autogen.sh
  - sh configure
  - make
  - make check
  - sudo make install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - clang++-3.8
