sudo: required
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - git clone https://github.com/bblanchon/ArduinoJson.git
  - cd ArduinoJson
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

  - git clone https://github.com/libical/libical.git
  - cd libical
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

  - git clone https://github.com/wolfSSL/wolfssl.git
  - cd wolfssl
  - sh autogen.sh
  - sh configure
  - make
  - make check
  - sudo make install
